### ISSUE TITLE
NPM Entry still points to biesbjerg

### ISSUE THREAD

**Issue by daniel-bikemap** [FJNR-inc/ngx-translate-po-http-loader#4]
Install instructions at https://www.npmjs.com/package/@fjnr/ngx-translate-po-http-loader still point to biesbjerg:
`npm i @biesbjerg/ngx-translate-po-http-loader --save`.

**Comment by RignonNoel** [comment]
Sorry for the delay, i didn't see the notification. PR #3 fixed the problem but thanks for the issue.
